FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances
COPY requirements.dhcp.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Installation de sudo
RUN apt-get update && apt-get install -y sudo && apt-get clean

# Copie du code source
COPY . .

# Commande de démarrage avec sudo
CMD ["sudo", "python3", "manage.py", "rundhcp"]