# Generated by Django 5.1.6 on 2025-02-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.GenericIPAddressField()),
                ('min_ip_pool', models.GenericIPAddressField()),
                ('max_ip_pool', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('interface', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='app.template')),
            ],
            options={
                'unique_together': {('serial_number', 'interface')},
            },
        ),
    ]
