# Generated by Django 5.1.6 on 2025-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='device',
            name='configured',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='device',
            name='interface',
        ),
    ]
