# Generated by Django 5.1.7 on 2025-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="default_gateway",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="subnet_mask",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
