# Generated by Django 5.1.6 on 2025-02-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_template_name_alter_device_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='file_path',
        ),
        migrations.AddField(
            model_name='template',
            name='file',
            field=models.FileField(null=True, upload_to='conf/'),
        ),
    ]
