# Generated by Django 5.1.7 on 2025-04-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_device_default_gateway_device_ip_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="ip_address",
        ),
    ]
