"""
Django settings for webZtp project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import env.config as cfg


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = cfg.SECRET_KEY


ALLOWED_HOSTS = cfg.ALLOWED_HOSTS_LIST

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "django_cotton",
    "crispy_forms",
    "crispy_bootstrap5",
    "device",
    "monitoring",
    "user",
    "core",
]


# allauth Settings
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# Configuration correcte pour django-allauth selon la documentation
ACCOUNT_LOGIN_METHOD = "username"
ACCOUNT_SIGNUP_FIELDS = ["username*", "password1*", "password2*"]
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_SIGNUP_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# Configuration "Remember Me" - selon la doc django-allauth moderne
ACCOUNT_SESSION_REMEMBER = None  # Permet à l'utilisateur de choisir avec la checkbox
ACCOUNT_REMEMBER_ME = None  # None = affiche la checkbox, True = force activé, False = désactivé

# Sécurité login - nouvelle syntaxe django-allauth
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m/ip',  # 5 tentatives max par 5 minutes par IP
}

# Crispy Forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

# Configuration pour reverse proxy
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
# Commenté pour empêcher la détection automatique HTTPS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = "webZtp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": False,
        "OPTIONS": {
            "loaders": [
                "django_cotton.cotton_loader.Loader",
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
            ],
        },
    },
]

WSGI_APPLICATION = "webZtp.wsgi.application"


if cfg.IS_PRODUCTION:
    # Production security settings
    CSRF_TRUSTED_ORIGINS = [
        f"https://{cfg.HOSTNAME}:{cfg.HTTPS_PORT}",
        f"http://{cfg.HOSTNAME}:{cfg.HTTP_PORT}",
        f"http://localhost:{cfg.HTTP_PORT}",
        f"http://127.0.0.1:{cfg.HTTP_PORT}",
        f"http://localhost:8080",
        f"http://127.0.0.1:8080",
        "http://172.16.10.30:8080",
        "http://10.30.31.30:8080",
    ]

    # CSRF Configuration pour reverse proxy
    CSRF_USE_SESSIONS = True  # Utilise les sessions pour le CSRF
    CSRF_COOKIE_HTTPONLY = False  # Permet au JS d'accéder au cookie CSRF
    CSRF_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = False  # Important: False pour HTTP
    CSRF_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 jours

    # Security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Session security
    SESSION_COOKIE_SECURE = False  # Changé à False pour HTTP
    SESSION_COOKIE_HTTPONLY = True

    # Database
    # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": cfg.DB_NAME,
            "USER": cfg.DB_USER,
            "PASSWORD": cfg.DB_PASSWORD,
            "HOST": cfg.DB_HOST,
            "PORT": cfg.DB_PORT,
        }
    }
else:
    DEBUG = True

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Europe/Paris"
USE_TZ = True

USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User-uploaded content)

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "auth.User"

LOGIN_URL = "/login/"

# --- Configuration de session unifiée pour éviter les déconnexions ---
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Utilise la DB pour les sessions
SESSION_COOKIE_NAME = 'webztp_sessionid'  # Nom personnalisé pour éviter les conflits
SESSION_COOKIE_SAMESITE = 'Lax'  # Protection CSRF tout en gardant la compatibilité
SESSION_COOKIE_HTTPONLY = True  # Sécurité : empêche l'accès JS aux cookies de session
SESSION_COOKIE_SECURE = False  # False pour HTTP, True pour HTTPS
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 jours par défaut
SESSION_SAVE_EVERY_REQUEST = True  # Prolonge la session à chaque requête
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Sessions persistantes même après fermeture navigateur

# Configuration CSRF unifiée
CSRF_USE_SESSIONS = True  # Utilise les sessions pour stocker les tokens CSRF
CSRF_COOKIE_HTTPONLY = False  # Permet au JS d'accéder au cookie CSRF si nécessaire
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # False pour HTTP
CSRF_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 jours

# Configuration spéciale pour le "Remember Me" de django-allauth
# Quand l'utilisateur coche "Se souvenir de moi", la session dure plus longtemps
ACCOUNT_SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 jours si "remember me" coché
