FROM python:3.9

WORKDIR /service

COPY ./requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . . 
ENV PORT=67
EXPOSE 67

CMD ["python3", "dhcp_server.py"]