# Generated by Django 5.1.7 on 2025-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
