# Generated by Django 5.1.7 on 2025-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_alter_device_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="hostname",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
