# Generated by Django 5.1.7 on 2025-07-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_alter_device_hostname"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="template_variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Valeurs des variables du template associé",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Variables extraites automatiquement du template Jinja2",
            ),
        ),
    ]
