# Generated by Django 5.1.7 on 2025-07-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_device_template_variables_template_variables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="default_gateway",
        ),
        migrations.RemoveField(
            model_name="device",
            name="login",
        ),
        migrations.RemoveField(
            model_name="device",
            name="password",
        ),
        migrations.RemoveField(
            model_name="device",
            name="subnet_mask",
        ),
    ]
